rest:
  ssl: true
  host: lab.d2t.co
  port: 443
  nameSpace: /serverspu

# Search settings
search: 
  # Settings to enable/disable or configure advanced search filters.
  advancedFilters:
    enabled: true
    # List of filters to enable in "Advanced Search" dropdown
    filter: [ 'bastaNumber', 'goswaraNumber', 'firnumber', 'firyear', 'title', 'location', 'policeStationname', 'barcode', 'filename' ]